name: barokat
description: "Meal and recycled meal products"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  equatable: ^2.0.5
  internet_connection_checker_plus: ^2.5.2
  flutter_svg: ^2.0.14
  keyboard_dismisser: ^3.0.0
  cached_network_image: ^3.4.1
  device_preview: ^1.2.0
  shared_preferences: ^2.3.3
  local_auth: ^2.3.0
  pinput: ^5.0.0
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  mask_text_input_formatter: ^2.9.0
  flutter_animator: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0





flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/platform/
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
  class_name: AppLocalization
  arb-dir: lib/localization/l10n
  template-arb-file: intl_uz.arb
  preferred-supported-locales:
    - uz
    - en
    - ru
  use-deferred-loading: true